import {db} from "./db.js"

const filmes = [
    {
        img: "img/ranking/o-poderoso-chefao.webp",
        titulo: "O Poderoso Chefão",
        genero: "Drama",
        direcao: "Francis Ford Coppola",
        sinopse: "Uma família mafiosa luta para estabelecer sua supremacia nos Estados Unidos depois da Segunda Guerra Mundial. Uma tentativa de assassinato deixa o chefão Vito Corleone incapacitado e força os filhos Michael e Sonny a assumir os negócios.",
        adicao: '2025-01-01',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/90/95/62/20122008.jpg",
        titulo: "De Volta para o Futuro",
        genero: "Aventura, Comédia, Ficção Científica",
        direcao: "Robert Zemeckis",
        sinopse: "Um jovem (Michael J. Fox) aciona acidentalmente uma máquina do tempo construída por um cientista (Christopher Lloyd) em um Delorean, retornando aos anos 50. Lá conhece sua mãe (Lea Thompson), antes ainda do casamento com seu pai, que fica apaixonada por ele. Tal paixão põe em risco sua própria existência, pois alteraria todo o futuro, forçando-o a servir de cupido entre seus pais.",
        adicao: '2025-01-01',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/pictures/17/10/04/19/01/4966397.jpg",
        titulo: "Your Name",
        genero: "Animação, Romance, Fantasia",
        direcao: "Makoto Shinkai",
        sinopse: "Mitsuha Miyamizu é uma jovem que mora no interior do Japão e que deseja deixar sua pequena cidade para trás para tentar a sorte em Tóquio. Taki Tachibana, um jovem que trabalha em um restaurante em Tóquio, deseja largar o seu emprego para tentar se tornar um arquiteto. Os dois não se conhecem, mas estão direta e misteriosamente conectados pelas imagens de seus sonhos.",
        adicao: '2025-01-03',
    },
    {
        img: "img/ranking/um-sonho-de-liberdade.jpg",
        titulo: "Um Sonho de Liberdade",
        genero: "Drama",
        direcao: "Frank Darabont",
        sinopse: "Andy Dufresne é condenado a duas prisões perpétuas consecutivas pelas mortes de sua esposa e de seu amante. Porém, só Andy sabe que ele não cometeu os crimes. No presídio, durante dezenove anos, ele faz amizade com Red, sofre as brutalidades da vida na cadeia, se adapta, ajuda os carcereiros, etc.",
        adicao: '2025-01-03',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/pictures/14/10/31/20/39/476171.jpg",
        titulo: "Interestelar",
        genero: "Ficção Científica, Drama",
        direcao: "Christopher Nolan",
        sinopse: "As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand, Jenkins e Doyle, ele seguirá em busca de um novo lar.",
        adicao: '2025-01-03',
    },
    {
        img: "img/ranking/a-lista-de-schindler.jpg",
        titulo: "A Lista de Schindler",
        genero: "Drama",
        direcao: "Steven Spielberg",
        sinopse: "Oskar Schindler era um sujeito oportunista, sedutor, simpático, comerciante no mercado negro, mas, acima de tudo, um homem que se relacionava muito bem com o regime nazista, tanto que era membro do Partido Nazista. No entanto, apesar dos seus defeitos, amava o ser humano e assim fez o impossível, a ponto de perder a sua fortuna mas conseguir salvar mais de mil judeus dos campos de concentração.",
        adicao: '2025-01-17',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/pictures/15/05/14/21/14/504650.jpg",
        titulo: "Alien, o 8º Passageiro",
        genero: "Terror, Ficção Científica",
        direcao: "Ridley Scott",
        sinopse: "Uma nave espacial, ao retornar para Terra, recebe estranhos sinais vindos de um asteróide. Ao investigarem o local, um dos tripulantes é atacado por um estranho ser. O que parecia ser um ataque isolado se transforma em um terror constante, pois o tripulante atacado levou para dentro da nave o embrião de um alienígena, que não para de crescer e tem como meta matar toda a tripulação.",
        adicao: '2025-01-18',
    },    
    {
        img: "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/89/56/94/20055685.jpg",
        titulo: "Titanic",
        genero: "Romance, Drama",
        direcao: "James Cameron",
        sinopse: "Um artista pobre e uma jovem rica se conhecem e se apaixonam na fatídica viagem inaugural do Titanic em 1912. Embora esteja noiva do arrogante herdeiro de uma siderúrgica, a jovem desafia sua família e amigos em busca do verdadeiro amor.",
        adicao: '2025-01-18',
    },    
    {
        img: "https://br.web.img2.acsta.net/c_310_420/medias/nmedia/18/87/87/75/19962458.jpg",
        titulo: "O Auto da Compadecida",
        genero: "Comédia, Aventura",
        direcao: "Guel Arraes",
        sinopse: "As aventuras João Grilo (Matheus Natchergaele), um sertanejo pobre e mentiroso, e Chicó (Selton Mello), o mais covarde dos homens. Ambos lutam pelo pão de cada dia e atravessam por vários episódios enganando a todos da pequena cidade de Taperoá, no sertão da Paraíba. A salvação da dupla acontece com a aparição da Nossa Senhora (Fernanda Montenegro). Adaptação da obra de Ariano Suassuna.",
        adicao: '2025-01-18',
    }, 
    {
        img: "https://br.web.img3.acsta.net/c_310_420/pictures/23/05/08/10/29/0695770.jpg",
        titulo: "Oppenheimer",
        genero: "Ficção Científica, Drama",
        direcao: "Christopher Nolan",
        sinopse: "A trama é baseada na vida de J. Robert Oppenheimer, o físico teórico que liderou o Projeto Manhattan durante a Segunda Guerra Mundial, responsável pelo desenvolvimento das primeiras bombas atômicas. O filme acompanha a jornada de Oppenheimer, interpretado por Cillian Murphy, desde seus estudos até os desafios e dilemas morais enfrentados durante a criação da arma nuclear.",
        adicao: '2025-01-18',
    }, 
    {
        img: "img/ranking/forrest-gump.webp",
        titulo: "Forrest Gump - O Contador de Histórias",
        genero: "Comédia, Romance",
        direcao: "Robert Zemeckis",
        sinopse: "Mesmo com o raciocínio lento, Forrest Gump nunca se sentiu desfavorecido. Graças ao apoio da mãe, ele teve uma vida normal. Seja no campo de futebol como um astro do esporte, lutando no Vietnã ou como capitão de um barco de pesca de camarão, Forrest inspira a todos com seu otimismo. Mas a pessoa que Forrest mais ama pode ser a mais difícil de salvar: seu amor de infância, a doce e perturbada Jenny.",
        adicao: '2025-01-22',
    },
    {
        img: "img/ranking/o-rei-leao.jpg",
        titulo: "O Rei Leão",
        genero: "Animação, Aventura",
        direcao: "Roger Allers, Rob Minkoff",
        sinopse: "O Rei Leão narra a jornada de Simba, um jovem leão, que enfrenta desafios e traições para assumir seu lugar legítimo como rei da savana após a morte de seu pai. Com a ajuda de amigos, ele aprende sobre coragem e responsabilidade, retornando para restaurar a paz em seu reino.",
        adicao: '2025-02-01',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/92/91/32/20224832.jpg",
        titulo: "O Senhor dos Anéis - A Sociedade do Anel",
        genero: "Fantasia, Aventura",
        direcao: "Peter Jackson",
        sinopse: "Em uma terra fantástica, um hobbit recebe de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para seguir nesta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, e esses nove seres formam a Sociedade do Anel.",
        adicao: '2025-02-01',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/92/34/89/20194741.jpg",
        titulo: "O Senhor dos Anéis - As Duas Torres",
        genero: "Fantasia, Aventura",
        direcao: "Peter Jackson",
        sinopse: "Após a captura de Merry (Dominic Monaghan) e Pippy (Billy Boyd) pelos orcs, a Sociedade do Anel é dissolvida. Enquanto que Frodo (Elijah Wood) e Sam (Sean Astin) seguem sua jornada rumo à Montanha da Perdição para destruir o Um Anel, Aragorn (Viggo Mortensen), Legolas (Orlando Bloom) e Gimli (John Rhys-Davies) partem para resgatar os hobbits sequestrados.",
        adicao: '2025-02-01',
    },
    {
        img: "img/ranking/o-senhor-dos-aneis.jpg",
        titulo: "O Senhor dos Anéis - O Retorno do Rei",
        genero: "Fantasia, Aventura",
        direcao: "Peter Jackson",
        sinopse: "Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel.",
        adicao: '2025-02-02',
    },
    {
        img: "img/ranking/a-vida-e-bela.jpg",
        titulo: "A Vida é Bela",
        genero: "Drama, Comédia",
        direcao: "Roberto Benigni",
        sinopse: "Durante a Segunda Guerra Mundial na Itália, o judeu Guido (Roberto Benigni) e seu filho Giosué são levados para um campo de concentração nazista. Afastado da mulher, ele tem que usar sua imaginação para fazer o menino acreditar que estão participando de uma grande brincadeira, com o intuito de protegê-lo do terror e da violência que os cercam.",
        adicao: '2025-01-23',
    },
    {
        img: "img/ranking/a-espera-de-um-milagre.webp",
        titulo: "A Espera de um Milagre",
        genero: "Drama, Fantasia",
        direcao: "Frank Darabont",
        sinopse: "1935, no corredor da morte de uma prisão sulista. Paul Edgecomb (Tom Hanks) é o chefe de guarda da prisão, que tem John Coffey (Michael Clarke Duncan) como um de seus prisioneiros. Aos poucos, desenvolve-se entre eles uma relação incomum, baseada na descoberta de que o prisioneiro possui um dom mágico que é, ao mesmo tempo, misterioso e milagroso.",
        adicao: '2025-02-10',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/pictures/17/03/30/22/44/345288.jpg",
        titulo: "It - A Coisa",
        genero: "Terror",
        direcao: "Andy Muschietti",
        sinopse: 'Em It - A Coisa, um grupo de sete adolescentes de Derry, uma cidade no Maine, formam o auto-intitulado "Losers Club" - o clube dos perdedores. A pacata rotina da cidade é abalada quando crianças começam a desaparecer e tudo o que pode ser encontrado delas são partes de seus corpos. Logo, os integrantes do "Losers Club" acabam ficando face a face com o responsável pelos crimes: o palhaço Pennywise.',
        adicao: '2025-02-10',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/pictures/19/08/14/16/00/5320567.jpg",
        titulo: "It - Capítulo 2",
        genero: "Terror",
        direcao: "Andy Muschietti",
        sinopse: 'Vinte e sete anos depois dos eventos que chocaram os adolescentes que faziam parte do Clube dos Perdedores, os amigos realizam uma reunião. No entanto, o reencontro se torna uma verdadeira e sangrenta batalha quando Pennywise, o palhaço, retorna.',
        adicao: '2025-02-10',
    },
    {
        img: "img/ranking/batman.jpg",
        titulo: "Batman - O Cavaleiro das Trevas",
        genero: "Ação",
        direcao: "Christopher Nolan",
        sinopse: "Batman tem conseguido manter a ordem em Gotham com a ajuda de Jim Gordon e Harvey Dent. No entanto, um jovem e anárquico criminoso, conhecido apenas como Coringa, pretende testar o Cavaleiro das Trevas e mergulhar a cidade em um verdadeiro caos.",
        adicao: '2025-02-13',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/pictures/18/03/16/15/08/2019826.jpg",
        titulo: "Vingadores: Guerra Infinita",
        genero: "Ação, Ficção Científica",
        direcao: "Joe Russo, Anthony Russo",
        sinopse: "Em Vingadores: Guerra Infinita, Thanos (Josh Brolin) enfim chega à Terra, disposto a reunir as Joias do Infinito. Para enfrentá-lo, os Vingadores precisam unir forças com os Guardiões da Galáxia, ao mesmo tempo em que lidam com desavenças entre alguns de seus integrantes.",
        adicao: '2025-02-12',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/26/84/19873738.jpg",
        titulo: "O Exorcista",
        genero: "Terror",
        direcao: "William Friedkin",
        sinopse: "A história segue a jovem Regan MacNeil (Linda Blair), que começa a exibir comportamentos perturbadores e inexplicáveis. Sua mãe, Chris MacNeil (Ellen Burstyn), recorre a vários especialistas em busca de uma solução, mas quando todos os métodos falham, ela busca ajuda na Igreja.",
        adicao: '2025-01-25',
    },
    {
        img: "img/ranking/vingadores-ultimato.jpg",
        titulo: "Vingadores: Ultimato",
        genero: "Ação, Aventura, Ficção Científica",
        direcao: "Joe Russo, Anthony Russo",
        sinopse: "Após Thanos eliminar metade das criaturas vivas, os Vingadores têm de lidar com a perda de amigos e entes queridos. Com Tony Stark vagando perdido no espaço sem água e comida, Steve Rogers e Natasha Romanov lideram a resistência contra o titã louco.",
        adicao: '2025-01-23',
    },
    {
        img: "https://br.web.img2.acsta.net/c_310_420/img/af/d3/afd330bc4c617786bd0e2ac199487c80.PNG",
        titulo: "Alien: Romulus",
        genero: "Terror, Ficção Científica",
        direcao: "Fede Alvarez",
        sinopse: "Um grupo de jovens colonizadores espaciais se aventuram nas profundezas de uma estação espacial abandonada. Lá, eles descobrem uma forma de vida aterrorizante, forçando-os a lutar por sua sobrevivência.",
        adicao: '2025-01-23',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/img/b1/35/b1351babe7a777b7a97eded3db356990.jpg",
        titulo: "Ainda Estou Aqui",
        genero: "Drama",
        direcao: "Walter Salles",
        sinopse: '"Ainda Estou Aqui" é um filme brasileiro de 2024, dirigido por Walter Salles e estrelado por Fernanda Torres e Fernanda Montenegro. A trama é baseada na autobiografia de Marcelo Rubens Paiva e foca na vida de sua mãe, Eunice Paiva, uma advogada que se torna ativista política após a prisão e desaparecimento de seu marido, Rubens Paiva, durante a ditadura militar brasileira.',
        adicao: '2025-02-17',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/img/e8/f2/e8f24b869f741946d906755319d1b213.jpg",
        titulo: "O Auto da Compadecida 2",
        genero: "Comédia, Aventura",
        direcao: "Guel Arraes, Flavia Lacerda",
        sinopse: 'Em "O Auto da Compadecida 2", João Grilo retorna à cidade de Taperoá após 20 anos e se envolve em novas trapaças e disputas políticas, enquanto seu amigo Chicó o acompanha em mais uma aventura repleta de confusões. Mais uma vez, eles precisam de uma intervenção divina para resolver seus problemas.',
        adicao: '2025-02-18',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/img/44/98/44981a8c47e8b871d4cafa3fd938bfd3.jpeg",
        titulo: "Dragon Ball DAIMA",
        genero: "Ação, Animação",
        direcao: "Aya Komaki, Yoshitaka Yashima",
        sinopse: 'A trama se passa entre os eventos de "Dragon Ball Z" e antes de "Dragon Ball Super", os personagens são transformados em crianças devido a uma conspiração. Para reverter essa situação, eles viajam para o Reino dos Demônios em busca de respostas e uma cura para a transformação',
        adicao: '2025-02-19',
    },    
    {
        img: "https://br.web.img2.acsta.net/c_310_420/img/73/f2/73f2ac521ab70153345878e928b6d64c.jpg",
        titulo: "Blindado",
        genero: "Ação",
        direcao: "Justin Routt",
        sinopse: '"Blindado" segue um guarda de segurança e seu filho enquanto enfrentam uma gangue de assaltantes que tenta roubar o carregamento valioso que transportam. A trama se desenrola com ação intensa e suspense.',
        adicao: '2025-02-20',
    },    
    {
        img: "https://br.web.img3.acsta.net/c_310_420/img/ae/76/ae760746629636d521b8e1aa5778935c.png",
        titulo: "Flow",
        genero: "Aventura, Animação, Fantasia",
        direcao: "Gints Zilbalodis",
        sinopse: "O filme se passa em um mundo pós-apocalíptico, onde um gato solitário tenta sobreviver após uma grande enchente que devastou seu lar. Durante sua jornada, ele encontra refúgio em um barco habitado por diversas espécies de animais. Juntos, eles enfrentam desafios e perigos enquanto navegam por paisagens místicas e tentam se adaptar a esse novo mundo inundado.",
        adicao: '2025-02-22',
    },
    {
        img: "https://br.web.img3.acsta.net/c_310_420/img/56/0c/560c72bf877f88472877898cebe00ff0.jpg",
        titulo: "Capitão América: Admirável Mundo Novo",
        genero: "Ação, Aventura, Ficção Científica",
        direcao: "Julius Onah",
        sinopse: 'Sam Wilson, interpretado por Anthony Mackie, assumindo o papel de Capitão América após os eventos de "Falcão e o Soldado Invernal". Ele enfrenta novos desafios e uma ameaça global, provando que está à altura do legado de Steve Rogers.',
        adicao: '2025-02-23',
    },
];

for(let x = 0; x < filmes.length; x++) {
    await db.run(`
        INSERT INTO filmes (id, img, titulo, direcao, sinopse, data_adicao) VALUES(?,?,?,?,?,?)
        `, [x, filmes[x].img, filmes[x].titulo, filmes[x].direcao, filmes[x].sinopse, filmes[x].adicao]
    )
    const generos = filmes[x].genero.split(", ")

    for (const genero of generos) {
        await db.run(`INSERT INTO genero_filme (idfilme, nomegenero) VALUES (?, ?)`, [x, genero])        
    }
}

console.log('filmes inserirdos');
